[tool.poetry]
name = "repl_python3_beta_Fri"
version = "0.1.0"
description = ""
authors = ["SeanMahady <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pyqt5 = "^5.15.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
